apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  # Scalable: Change replicas based on your environment
  # Dev/Test: 1 replica (minimum resources)
  # Staging: 2 replicas (moderate HA)
  # Production: 3+ replicas (full HA)
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
        class: local-path
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 3.8.0
    metadataVersion: 3.8-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      # Replication settings - adjust based on number of replicas
      # For 1 replica: set all to 1
      # For 3+ replicas: use 3, 3, 2, 3, 2 for production HA
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 2
      default.replication.factor: 2
      min.insync.replicas: 2
      # Auto-create topics with proper replication
      auto.create.topics.enable: true
    resources:
      requests:
        memory: 1Gi   # Reduced from 2Gi for better resource efficiency
        cpu: 250m     # Reduced from 500m
      limits:
        memory: 2Gi   # Reduced from 4Gi
        cpu: 1000m    # Reduced from 2000m
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 128Mi  # Reduced from 256Mi
          cpu: 50m       # Reduced from 100m
        limits:
          memory: 256Mi  # Reduced from 512Mi
          cpu: 250m      # Reduced from 500m
    userOperator:
      resources:
        requests:
          memory: 128Mi  # Reduced from 256Mi
          cpu: 50m       # Reduced from 100m
        limits:
          memory: 256Mi  # Reduced from 512Mi
          cpu: 250m      # Reduced from 500m
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-metrics
  namespace: kafka
data:
  kafka-metrics-config.yml: |
    lowercaseOutputName: true
    rules:
    - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
      name: kafka_server_$1_$2
      type: GAUGE
      labels:
       clientId: "$3"
       topic: "$4"
       partition: "$5"
    - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+), brokerPort=(.+)><>Value
      name: kafka_server_$1_$2
      type: GAUGE
      labels:
       clientId: "$3"
       broker: "$4:$5"
