apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui
  namespace: argocd
spec:
  project: default
  sources:
    - chart: kafka-ui
      repoURL: https://provectus.github.io/kafka-ui-charts
      targetRevision: 0.7.6
      helm:
        valueFiles:
          - $values/helm-values/kafka-ui/values.yaml
    - repoURL: https://github.com/avioralm/argocd-example-apps.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: false  # Prevent automatic deletion of resources
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
