apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  sources:
    - chart: minio
      repoURL: https://charts.min.io/
      targetRevision: 5.4.0
      helm:
        valueFiles:
          - $values/helm-values/minio/values.yaml
    - repoURL: https://github.com/avioralm/argocd-example-apps.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: false  # Prevent automatic deletion of resources
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
